### ISSUE TITLE
编译过程中，提示找不到GLOG_PATH

### ISSUE THREAD

**Issue by Ru1yi** [HuangCongQing/linefit_ground_segmentation_details#2]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GLOG_PATH
    linked by target "ground_segmentation_node" in directory /home/roy/plusgo/Perception/linefit_ground_segmentation_details-main/catkin_ws/src/linefit_ground_segmentation/linefit_ground_segmentation_ros
    linked by target "ground_segmentation_test_node" in directory /home/roy/plusgo/Perception/linefit_ground_segmentation_details-main/catkin_ws/src/linefit_ground_segmentation/linefit_ground_segmentation_ros

**Comment by wangshichang-726** [comment]
install glog

**Comment by wangshichang-726** [comment]
sudo apt-get update
sudo apt-get install libgoogle-glog-dev
